[COPY] --- ROCK-COPYRIGHT-NOTE-BEGIN ---
[COPY] 
[COPY] This copyright note is auto-generated by ./scripts/Create-CopyPatch.
[COPY] Please add additional copyright information _after_ the line containing
[COPY] the ROCK-COPYRIGHT-NOTE-END tag. Otherwise it might get removed by
[COPY] the ./scripts/Create-CopyPatch script. Do not edit this copyright text!
[COPY] 
[COPY] ROCK Linux: rock-src/package/daja77/soya/soya.cache
[COPY] ROCK Linux is Copyright (C) 1998 - 2006 Clifford Wolf
[COPY] 
[COPY] This program is free software; you can redistribute it and/or modify
[COPY] it under the terms of the GNU General Public License as published by
[COPY] the Free Software Foundation; either version 2 of the License, or
[COPY] (at your option) any later version. A copy of the GNU General Public
[COPY] License can be found at Documentation/COPYING.
[COPY] 
[COPY] Many people helped and are helping developing ROCK Linux. Please
[COPY] have a look at http://www.rocklinux.org/ and the Documentation/TEAM
[COPY] file for details.
[COPY] 
[COPY] --- ROCK-COPYRIGHT-NOTE-END ---

[TIMESTAMP] 1142626652 Fri Mar 17 21:17:32 2006 (5) ERROR
[TIMESTAMP] 1142894264 Mon Mar 20 23:37:44 2006 (9) ERROR
[TIMESTAMP] 1142962959 Tue Mar 21 18:42:39 2006 (5) ERROR
[TIMESTAMP] 1142973256 Tue Mar 21 21:34:16 2006 (9) ERROR
[TIMESTAMP] 1143032935 Wed Mar 22 14:08:55 2006 (5) ERROR
[TIMESTAMP] 1143042564 Wed Mar 22 16:49:24 2006 (9) ERROR

[CONFIG-ID] TRUNK-x86-reference
[ROCKVER] TRUNK

[LOGS] 5-soya.err 9-soya.err

[BUILDTIME] 5536 (5) ERROR
[BUILDTIME] 5740 (9) ERROR
[BUILDTIME] 5753 (5) ERROR
[BUILDTIME] 5762 (9) ERROR
[BUILDTIME] 5763 (5) ERROR
[BUILDTIME] 5759 (9) ERROR


[5-ERROR] _soya.c:74282: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74283: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74284: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74285: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74286: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74287: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[5-ERROR] _soya.c:74580: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74581: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74582: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74583: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74584: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74584: error: `__pyx_f_5_soya_11_Cal3dShape__set_face_neighborhood' undeclared (first use in this function)
[5-ERROR] _soya.c:74585: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74586: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74587: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74588: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74589: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74590: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74591: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74592: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:74593: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[5-ERROR] _soya.c:75412: error: `glColor4fv' undeclared (first use in this function)
[5-ERROR] _soya.c: At top level:
[5-ERROR] _soya.c:75724: error: conflicting types for '__Pyx_WriteUnraisable'
[5-ERROR] _soya.c:56149: error: previous declaration of '__Pyx_WriteUnraisable' was here
[5-ERROR] _soya.c:75724: error: conflicting types for '__Pyx_WriteUnraisable'
[5-ERROR] _soya.c:56149: error: previous declaration of '__Pyx_WriteUnraisable' was here
[5-ERROR] _soya.c:63859: error: storage size of `__pyx_vtable_5_soya__Image' isn't known
[5-ERROR] _soya.c:67762: error: storage size of `__pyx_vtable_5_soya__Cal3dShape' isn't known
[5-ERROR] {standard input}: Assembler messages:
[5-ERROR] {standard input}:12835: Error: symbol `__pyx_k225' is already defined
[5-ERROR] {standard input}:12836: Error: symbol `__pyx_1' is already defined
[5-ERROR] {standard input}:12853: Error: symbol `__pyx_v_new_pixels' is already defined
[5-ERROR] {standard input}:12855: Error: symbol `__pyx_2' is already defined
[5-ERROR] {standard input}:12940: Error: symbol `__pyx_r' is already defined
[5-ERROR] {standard input}:12951: Error: symbol `__pyx_r' is already defined
[5-ERROR] {standard input}:12958: Error: symbol `__pyx_1' is already defined
[5-ERROR] {standard input}:12964: Error: symbol `__pyx_2' is already defined
[5-ERROR] error: command 'gcc-34' failed with exit status 1
[5-ERROR] --- BUILD ERROR ---
[5-ERROR] Creating file list and doing final adaptions ... 
[5-ERROR] Processing static lib corrections ...
[5-ERROR] Verifing the .la files ...
[5-ERROR] Found 0 files for this package.
[5-ERROR] Applying package split: 40 soya:dev (/lib/.*\.(la|a|o)$|/include/)
[5-ERROR] Applying package split: 42 soya:dev /pkgconfig/
[5-ERROR] Applying package split: 60 soya:doc /share/doc/
[5-ERROR] Calculating package dependencies ...
[5-ERROR] Making post-install adaptions.
[5-ERROR] Finished building soya=soya.

[9-ERROR] _soya.c:74282: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74283: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74284: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74285: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74286: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74287: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Image'
[9-ERROR] _soya.c:74580: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74581: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74582: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74583: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74584: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74584: error: `__pyx_f_5_soya_11_Cal3dShape__set_face_neighborhood' undeclared (first use in this function)
[9-ERROR] _soya.c:74585: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74586: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74587: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74588: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74589: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74590: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74591: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74592: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:74593: error: invalid use of undefined type `struct __pyx_vtabstruct_5_soya__Cal3dShape'
[9-ERROR] _soya.c:75412: error: `glColor4fv' undeclared (first use in this function)
[9-ERROR] _soya.c: At top level:
[9-ERROR] _soya.c:75724: error: conflicting types for '__Pyx_WriteUnraisable'
[9-ERROR] _soya.c:56149: error: previous declaration of '__Pyx_WriteUnraisable' was here
[9-ERROR] _soya.c:75724: error: conflicting types for '__Pyx_WriteUnraisable'
[9-ERROR] _soya.c:56149: error: previous declaration of '__Pyx_WriteUnraisable' was here
[9-ERROR] _soya.c:63859: error: storage size of `__pyx_vtable_5_soya__Image' isn't known
[9-ERROR] _soya.c:67762: error: storage size of `__pyx_vtable_5_soya__Cal3dShape' isn't known
[9-ERROR] {standard input}: Assembler messages:
[9-ERROR] {standard input}:12835: Error: symbol `__pyx_k225' is already defined
[9-ERROR] {standard input}:12836: Error: symbol `__pyx_1' is already defined
[9-ERROR] {standard input}:12853: Error: symbol `__pyx_v_new_pixels' is already defined
[9-ERROR] {standard input}:12855: Error: symbol `__pyx_2' is already defined
[9-ERROR] {standard input}:12940: Error: symbol `__pyx_r' is already defined
[9-ERROR] {standard input}:12951: Error: symbol `__pyx_r' is already defined
[9-ERROR] {standard input}:12958: Error: symbol `__pyx_1' is already defined
[9-ERROR] {standard input}:12964: Error: symbol `__pyx_2' is already defined
[9-ERROR] error: command 'gcc-34' failed with exit status 1
[9-ERROR] --- BUILD ERROR ---
[9-ERROR] Creating file list and doing final adaptions ... 
[9-ERROR] Processing static lib corrections ...
[9-ERROR] Verifing the .la files ...
[9-ERROR] Found 0 files for this package.
[9-ERROR] Applying package split: 40 soya:dev (/lib/.*\.(la|a|o)$|/include/)
[9-ERROR] Applying package split: 42 soya:dev /pkgconfig/
[9-ERROR] Applying package split: 60 soya:doc /share/doc/
[9-ERROR] Calculating package dependencies ...
[9-ERROR] Making post-install adaptions.
[9-ERROR] Finished building soya=soya.

